#ifndef __DRIVE_MOSSWITCH_H__
#define __DRIVE_MOSSWITCH_H__

extern void Drive_MosSwitch_OFF(void);
extern void Drive_MosSwitch210_PWMOut(void);
extern void Drive_MosSwitch245_PWMOut(void);
extern void Drive_MosSwitch_SetDuty(uint16_t duty);

#define MAX_PWM_PRIOD 10000

#define MOSSWITCH_GPIOB_PIN        GPIO_PIN_5
#define MOSSWITCH_GPIOA_PIN        GPIO_PIN_7
#define MOSSWITCH_GPIOB_PORT       GPIOB
#define MOSSWITCH_GPIOA_PORT       GPIOA
#define MOSSWITCH_GPIO_AF_TIM3     GPIO_AF1_TIM3

#define MOSSWITCH_GPIO_MODE_OUT    GPIO_MODE_OUTPUT_PP
#define MOSSWITCH_GPIO_MODE_AF     GPIO_MODE_AF_PP
#define MOSSWITCH_GPIO_PULL        GPIO_NOPULL
#define MOSSWITCH_GPIO_SPEED       GPIO_SPEED_FREQ_HIGH

#define MOSSWITCH_TIM_INSTANCE     TIM3
#define MOSSWITCH_TIM_CHANNEL      TIM_CHANNEL_2
#define MOSSWITCH_TIM_PRESCALER    (4 - 1)
#define MOSSWITCH_TIM_PERIOD       MAX_PWM_PRIOD
#define MOSSWITCH_TIM_CLOCKDIV     TIM_CLOCKDIVISION_DIV1
#define MOSSWITCH_TIM_COUNTERMODE  TIM_COUNTERMODE_UP
#define MOSSWITCH_TIM_REPETITION   (1 - 1)
#define MOSSWITCH_TIM_AUTORELOAD   TIM_AUTORELOAD_PRELOAD_DISABLE

#define MOSSWITCH_PWM_OCMODE       TIM_OCMODE_PWM1
#define MOSSWITCH_PWM_OCPOLARITY   TIM_OCPOLARITY_HIGH
#define MOSSWITCH_PWM_OCFASTMODE   TIM_OCFAST_DISABLE
#define MOSSWITCH_PWM_OCNPOLARITY  TIM_OCNPOLARITY_HIGH
#define MOSSWITCH_PWM_OCNIDLE      TIM_OCNIDLESTATE_RESET
#define MOSSWITCH_PWM_OCIDLE       TIM_OCIDLESTATE_RESET
#define MOSSWITCH_PWM_PULSE        0

#endif
